run:
  timeout: 10m

linters:
  enable-all: false
  enable:
    - durationcheck
    # - depguard
    - errcheck
    - gci
    - gofumpt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - tenv
    - unconvert
    - unused
    - paralleltest
    - wastedassign
    - whitespace
issues:
  exclude:
    - "unused-parameter: parameter"
    - "redefines-builtin-id:"
    - "exhaustive"
  exclude-dirs:
    - pkg/tf2pulumi/internal/addrs
    - pkg/tf2pulumi/internal/config
    - pkg/tf2pulumi/internal/configs
    - pkg/vendored
    # TODO(https://github.com/pulumi/pulumi-terraform-bridge/issues/2474)
    - pkg/pf/tests
    - pkg/tests
    - pkg/x/testing
    - pkg/x/muxer/tests
    - pf
    - x/muxer
    - testing
  exclude-rules:
    - path: pkg/tfgen/*
      linters:
        - prealloc
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/pulumi/pulumi-terraform-bridge)
    skip-generated: true
  paralleltest:
    ignore-missing-subtests: true
  nakedret:
    # Make an issue if func has more lines of code than this setting, and it has naked returns.
    # Default: 30
    max-func-lines: 60
  govet:
    enable:
      - nilness
      # Reject comparisons of reflect.Value with DeepEqual or '=='.
      - reflectvaluecompare
      # Reject sort.Slice calls with a non-slice argument.
      - sortslice
      # Detect write to struct/arrays by-value that aren't read again.
      - unusedwrite
  importas:
    alias:
    - pkg: github.com/pulumi/pulumi/sdk/v3/proto/go
      alias: pulumirpc
