run:
  skip-dirs:
    - pkg/tf2pulumi/internal/addrs
    - pkg/tf2pulumi/internal/config
    - pkg/tf2pulumi/internal/configs
  timeout: 10m

linters:
  enable-all: false
  enable:
    - errcheck
    - gofmt
    - gosec
    - govet
    - ineffassign
    - lll
    - megacheck
    - misspell
    - nakedret
    - nolintlint
    - revive
    - unconvert
    - unused
