run:
  timeout: 10m

linters:
  enable-all: false
  enable:
    - errcheck
    - gofmt
    - gci
    - gosec
    - govet
    - ineffassign
    - lll
    - gosimple
    - staticcheck
    - unused
    - misspell
    - nakedret
    - nolintlint
    - revive
    - unconvert
    - unused
issues:
  exclude:
    - "unused-parameter: parameter"
    - "redefines-builtin-id:"
  exclude-dirs:
    - pkg/tf2pulumi/internal/addrs
    - pkg/tf2pulumi/internal/config
    - pkg/tf2pulumi/internal/configs
    - pkg/vendored
    # TODO(https://github.com/pulumi/pulumi-terraform-bridge/issues/2474)
    - pf/tests
    - pkg/tests
    - testing
    - x/muxer/tests
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/pulumi/pulumi-terraform-bridge/v3)
    skip-generated: true
