version: "2"
linters:
  enable:
    - durationcheck
    - goheader
    - goprintffuncname
    - gosec
    - importas
    - lll
    - misspell
    - nakedret
    - nolintlint
    - paralleltest
    - revive
    - unconvert
    - wastedassign
    - whitespace
  settings:
    govet:
      enable:
        - nilness
        - reflectvaluecompare
        - sortslice
        - unusedwrite
    importas:
      alias:
        - pkg: github.com/pulumi/pulumi/sdk/v3/proto/go
          alias: pulumirpc
    nakedret:
      max-func-lines: 60
    paralleltest:
      ignore-missing-subtests: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
          - paralleltest
        path: pkg/pf/tests
      - linters:
          - lll
        path: pkg/tests
      - linters:
          - lll
          - paralleltest
        path: pkg/pf/tests
      - path: (.+)\.go$
        text: 'unused-parameter: parameter'
      - path: (.+)\.go$
        text: 'redefines-builtin-id:'
      - path: (.+)\.go$
        text: exhaustive
    paths:
      - pkg/tf2pulumi/internal/addrs
      - pkg/tf2pulumi/internal/config
      - pkg/tf2pulumi/internal/configs
      - pkg/vendored
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/pulumi/pulumi-terraform-bridge)
  exclusions:
    generated: lax
    paths:
      - pkg/tf2pulumi/internal/addrs
      - pkg/tf2pulumi/internal/config
      - pkg/tf2pulumi/internal/configs
      - pkg/vendored
      - third_party$
      - builtin$
      - examples$
