coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
ignore:
  - "pkg/vendored"
  # deprecated
  - "pkg/tfshim/tfplugin5"
  # scripts folder
  - "scripts"
  - "unstable/scripts"
  # test frameworks
  - "pkg/internal/tests"
  - "pkg/tests"
  - "pkg/pf/tests"
  - "pkg/x/testing"

