coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

ignore:
  # Integration test frameworks
  - "tests/"
  - "pkg/tests"
  - "pkg/internal/tests"
  - "pkg/pf/tests"
  # Deprecated module
  - "pf"
