permissions: write-all # Equivalent to default permissions plus id-token: write
name: Build and Test

on:
  workflow_call:
    inputs: {}
    secrets:
      CODECOV_TOKEN:
        required: false
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Note this needs to match the shard input to the test matrix below as well as pattern in exclude.
  # see jobs.test.strategy.matrix.{shard,exclude}
  TOTAL_SHARDS: 30
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: imports/github-secrets
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: false
  PULUMI_AUTOMATION_API_SKIP_VERSION_CHECK: true

jobs:
  test:
    strategy:
      # Collect all test failures instead of stopping when only one test is failing.
      fail-fast: false

      matrix:
        # To avoid depending on features introduced in newer golang versions, we need to
        # test our minimum supported golang versions.
        #
        # When we decide to bump our minimum go version, we need to remember to bump the
        # go version in our go.mod files.
        go-version: [1.23.x, 1.24.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        feature-flags: ["DEFAULT", "PULUMI_RAW_STATE_DELTA_ENABLED"]
        # Needs to match TOTAL_SHARDS
        shard: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
        exclude:
          # Windows and mac test runs do not need to be sharded as they are fast enough.
          # In order to do that we will skip all except the 0-th shard.
          - platform: windows-latest
            shard: 1
          - platform: windows-latest
            shard: 2
          - platform: windows-latest
            shard: 3
          - platform: windows-latest
            shard: 4
          - platform: windows-latest
            shard: 5
          - platform: windows-latest
            shard: 6
          - platform: windows-latest
            shard: 7
          - platform: windows-latest
            shard: 8
          - platform: windows-latest
            shard: 9
          - platform: windows-latest
            shard: 10
          - platform: windows-latest
            shard: 11
          - platform: windows-latest
            shard: 12
          - platform: windows-latest
            shard: 13
          - platform: windows-latest
            shard: 14
          - platform: windows-latest
            shard: 15
          - platform: windows-latest
            shard: 16
          - platform: windows-latest
            shard: 17
          - platform: windows-latest
            shard: 18
          - platform: windows-latest
            shard: 19
          - platform: windows-latest
            shard: 20
          - platform: windows-latest
            shard: 21
          - platform: windows-latest
            shard: 22
          - platform: windows-latest
            shard: 23
          - platform: windows-latest
            shard: 24
          - platform: windows-latest
            shard: 25
          - platform: windows-latest
            shard: 26
          - platform: windows-latest
            shard: 27
          - platform: windows-latest
            shard: 28
          - platform: windows-latest
            shard: 29
          - platform: macos-latest
            shard: 1
          - platform: macos-latest
            shard: 2
          - platform: macos-latest
            shard: 3
          - platform: macos-latest
            shard: 4
          - platform: macos-latest
            shard: 5
          - platform: macos-latest
            shard: 6
          - platform: macos-latest
            shard: 7
          - platform: macos-latest
            shard: 8
          - platform: macos-latest
            shard: 9
          - platform: macos-latest
            shard: 10
          - platform: macos-latest
            shard: 11
          - platform: macos-latest
            shard: 12
          - platform: macos-latest
            shard: 13
          - platform: macos-latest
            shard: 14
          - platform: macos-latest
            shard: 15
          - platform: macos-latest
            shard: 16
          - platform: macos-latest
            shard: 17
          - platform: macos-latest
            shard: 18
          - platform: macos-latest
            shard: 19
          - platform: macos-latest
            shard: 20
          - platform: macos-latest
            shard: 21
          - platform: macos-latest
            shard: 22
          - platform: macos-latest
            shard: 23
          - platform: macos-latest
            shard: 24
          - platform: macos-latest
            shard: 25
          - platform: macos-latest
            shard: 26
          - platform: macos-latest
            shard: 27
          - platform: macos-latest
            shard: 28
          - platform: macos-latest
            shard: 29
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@v1
      - name: Install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: Check out source code
        uses: actions/checkout@master
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: |
            **/go.sum
          # disable caching on windows because it's very slow
          # see https://github.com/actions/setup-go/issues/495
          cache: ${{ matrix.platform != 'windows-latest' }}
      - name: Find pulumi version
        id: pulumi_version
        shell: bash
        run: |
          GO_MODULE_VERSION=$(go list -m -f '{{.Version}}' github.com/pulumi/pulumi/pkg/v3)
          GO_VERSION=$(echo "$GO_MODULE_VERSION" | sed 's/^v//')
          echo "pulumi_version=$GO_VERSION"
          echo "pulumi_version=$GO_VERSION" >> $GITHUB_OUTPUT
      - name: Install pulumi
        uses: pulumi/actions@v5
        with:
          pulumi-version: ${{ steps.pulumi_version.outputs.pulumi_version }}
      - name: export feature flags
        run: echo ${{ matrix.feature-flags }}=true >> $GITHUB_ENV
        if: ${{ matrix.platform != 'windows-latest' && matrix.feature-flags != 'DEFAULT' }}
      - name: Build
        run: make build
      - name: Build PF
        run: cd pkg/pf && make build
      - name: Shard tests
        run: echo "RUN_TEST_CMD=$(go run github.com/pulumi/shard@0c8eaa6 --total ${{ env.TOTAL_SHARDS }} --index ${{ matrix.shard }} --seed 314 --error-on-name-clash)" >> $GITHUB_ENV
        if: ${{ matrix.platform == 'ubuntu-latest' }}
      - name: Test
        run: make test
      - name: Upload coverage reports to Codecov
        # If we have a CODECOV_TOKEN secret, then we upload it to get a coverage report.
        #
        # Community contributors do not have access to the CODECOV_TOKEN, so we just skip
        # this step.
        if: ${{ env.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ steps.esc-secrets.outputs.CODECOV_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@master
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
          cache-dependency-path: |
            **/go.sum
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          skip-cache: true
          version: v2.1
      - name: Lint
        run: make lint
  version-check:
    name: Verify Pulumi Version Consistency
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          check-latest: true
  sentinel:
    name: sentinel
    if: github.event_name == 'repository_dispatch' || github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      statuses: write
    needs:
    - test
    - lint
    runs-on: ubuntu-latest
    steps:
    - uses: guibranco/github-status-action-v2@0849440ec82c5fa69b2377725b9b7852a3977e76 # v1.1.13
      with:
        authToken: ${{secrets.GITHUB_TOKEN}}
        # Write an explicit status check called "Sentinel" which will only pass if this code really runs.
        # This should always be a required check for PRs.
        context: 'Sentinel'
        description: 'All required checks passed'
        state: 'success'
        # Write to the PR commit SHA if it's available as we don't want the merge commit sha,
        # otherwise use the current SHA for any other type of build.
        sha: ${{ github.event.pull_request.head.sha || github.sha }}
