name: Build and Test

on:
  workflow_call:
    inputs: {}
    secrets:
      CODECOV_TOKEN:
        required: false
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    strategy:
      matrix:
        # To avoid depending on features introduced in newer golang versions, we need to
        # test our minimum supported golang versions.
        #
        # When we decide to bump our minimum go version, we need to remember to bump the
        # go version in our go.mod files.
        go-version: [1.22.x, 1.23.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        feature-flags: ["DEFAULT", "PULUMI_TF_BRIDGE_ACCURATE_BRIDGE_PREVIEW"]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install pulumi
        uses: pulumi/actions@v5
        with:
          pulumi-version: dev
      - name: Check out source code
        uses: actions/checkout@master
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: |
            **/go.sum
      - name: export feature flags
        run: echo ${{ matrix.feature-flags }}=true >> $GITHUB_ENV
        if: ${{ matrix.platform != 'windows-latest' && matrix.feature-flags != 'DEFAULT' }}
      - name: export feature flags
        run: echo ${{ matrix.feature-flags }}=true >> $env:GITHUB_ENV
        if: ${{ matrix.platform == 'windows-latest' && matrix.feature-flags != 'DEFAULT' }}
      - name: Build
        run: make build
      - name: Build PF
        run: cd pf && make build
      - name: Test
        run: make test
      - name: Test PF
        run: cd pf && make test
      - name: Test Dynamic
        run: cd dynamic && make test
      - name: Upload coverage reports to Codecov
        # If we have a CODECOV_TOKEN secret, then we upload it to get a coverage report.
        #
        # Community contributors do not have access to the CODECOV_TOKEN, so we just skip
        # this step.
        if: ${{ env.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@master
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
          cache-dependency-path: |
            **/go.sum
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
            skip-cache: true
            skip-pkg-cache: true
            skip-build-cache: true
            version: v1.60
      - name: Lint
        run: make lint
