permissions: write-all # Equivalent to default permissions plus id-token: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Pull Request

on: [pull_request]

jobs:
  build:
    name: Test and Lint
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
  clean-files:
    name: Ensure test assets build cleanly
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@master
      - name: Setup mise
        uses: jdx/mise-action@c1a019b8d2586943b4dbebc456323b516910e310
        env:
          MISE_FETCH_REMOTE_VERSIONS_TIMEOUT: 30s
        with:
          version: 2026.2.20
          github_token: ${{ env.GITHUB_TOKEN }}
          # only saving the cache in the prerequisites job
          cache_save: true
      - run: make -C pkg/pf build.testproviders
      - name: Ensure Clean Repo
        run: git diff-files --quiet
      - name: Show Dirty Repo File Changes
        if: failure()
        run: git diff-files --patch
